formatter: markdown table

header-from: main.tf


output:
  file: "README.md"
  mode: replace
  template: |-
    # terraform-cloudflare-browser-ssh

    This is a simple terraform modules that creates a tunnel to a host using Cloudflare's browser ssh.
    Includes a configured Tunnel, Access Application, and SSH CA certificate.
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


settings:
  lockfile: false